core/urls.py
from django.urls import path
from . import views

app_name = "core"
urlpatterns = [
    path("", views.index, name="home"),
    path("movies/<tmdb_id>", views.movie_detail_view, name="movie_detail"), 
]

movie_recommend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from django.views.static import serve


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("", include("userauths.urls")),

    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),

    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userauths/urls.py
from django.urls import path
from . import views

app_name = "userauths"

urlpatterns = [
    path('user/sign-up/', views.register_view, name= "sign-up"),
    path('user/sign-in/', views.login_view, name="sign-in"),
    path('account/', views.account_view, name="account"),
    path('logout', views.logout_view, name="logout"),
]

templates/user/login.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="dark">


<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>StreamIT | Responsive Bootstrap 5 Template</title>
  <!-- Google Font Api KEY-->
  <meta name="google_font_api" content="AIzaSyBG58yNdAjc20_8jAvLNSVi9E4Xhwjau_k">
  
  <!-- Favicon -->
  <link rel="shortcut icon" href="assets/images/favicon.ico" />
  
  <!-- Library / Plugin Css Build -->
  <link rel="stylesheet" href="{% static 'assets/css/core/libs.min.css' %}" />
  
  <!-- font-awesome css -->
  <link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/all.min.css' %}" />
  
  <!-- Iconly css -->
  <link rel="stylesheet" href="{% static 'assets/vendor/iconly/css/style.css' %}" />
  
  <!-- Animate css -->
  <link rel="stylesheet" href="{% static 'assets/vendor/animate.min.css' %}" />
  
  
  
  
  
  
  <!-- Streamit Design System Css -->
  <link rel="stylesheet" href="{% static "assets/css/streamit.min848f.css" %}" />
  
  <!-- Custom Css -->
  <link rel="stylesheet" href="{% static "assets/css/custom.min848f.css" %}" />
  
  <!-- Rtl Css -->
  <link rel="stylesheet" href="{% static "assets/css/rtl.min848f.css" %}" />
  
  <!-- Google Font -->
  <link rel="preconnect" href="https://fonts.googleapis.com/">
  <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,300&amp;display=swap" rel="stylesheet">
  
</head>

<body class="  ">
  <span class="screen-darken"></span>
  <!-- loader Start -->
   <!-- loader Start -->
  <div class="loader simple-loader">
     <div class="loader-body">
        <img src="{% static 'assets/images/loader.gif' %}" alt="loader" class="img-fluid " width="300">
      </div>
  </div>
  <!-- loader END -->  <!-- loader END -->
  <main class="main-content">
      <!--Nav Start-->
      <!--Nav End-->

      <!--bread-crumb-->
      <!--bread-crumb-->


<div class="vh-100"
    style="background: url('{% static "assets/images/pages/01.html" %}'); background-size: cover; background-repeat: no-repeat; position: relative;min-height:500px">
    <div class="container">
        <div class="row justify-content-center align-items-center height-self-center vh-100">
            <div class="col-lg-5 col-md-12 align-self-center">
                <div class="user-login-card bg-body">
                    <div class="text-center">
                        <!--Logo -->
                        <div class="logo-default">
                            <a class="navbar-brand text-primary" href="index.html"> 
                                <img class="img-fluid logo" src="{% static 'assets/images/logo.html' %}" loading="lazy" alt="streamit" />
                            </a>
                        </div>
                        <div class="logo-hotstar">
                            <a class="navbar-brand text-primary" href="index.html"> 
                                <img class="img-fluid logo" src="{% static 'assets/images/logo-hotstar.html' %}" loading="lazy" alt="streamit" />
                            </a>
                        </div> 
                        <div class="logo-prime">
                            <a class="navbar-brand text-primary" href="index.html"> 
                                <img class="img-fluid logo" src="{% static 'assets/images/logo-prime.html' %}" loading="lazy" alt="streamit" />
                            </a>
                        </div> 
                        <div class="logo-hulu">
                            <a class="navbar-brand text-primary" href="index.html"> 
                                <img class="img-fluid logo" src="{% static 'assets/images/logo-hulu.html' %}" loading="lazy" alt="streamit" />
                            </a>
                        </div>
                    </div>
                    <form action="" method="POST">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label class="text-white fw-500 mb-2">Email Address</label>
                            <input type="text" class="form-control rounded-1" name="email" placeholder="Johndoe@gmail.com" required="">
                        </div>
                        <div class="mb-3">
                            <label class="text-white fw-500 mb-2">Password</label>
                            <input type="password" class="form-control rounded-1" name="password" placeholder="********" required="">
                        </div>
                        
                        <label
                            class="list-group-item d-flex align-items-center mb-3 font-size-14 text-white fw-500"><input
                                class="form-check-input m-0 me-2" type="checkbox">Remember Me</label>
                                <div class="full-button">
                        <div class="iq-button">
                            <button class="btn btn-black d-block" id="loginBtn" type="submit">Log In</button>

                        </div>
                        </div>
                    </form>
                    <p class="my-4 text-center fw-500 text-white">New to Streamit? <a href="{% url "userauths:sign-up" %}"
                            class="text-primary ms-1">Register</a></p>
                    
                    
                </div>
            </div>
        </div>
    </div>
</div>

  </main>



  <div id="back-to-top" style="display: none;">
     <a class="p-0 btn bg-primary btn-sm position-fixed top border-0 rounded-circle text-white" id="top" href="#top">
        <i class="fa-solid fa-chevron-up"></i>
     </a>
  </div>
  <!-- Wrapper End-->
  <!-- Library Bundle Script -->
  <script src="{% static 'assets/js/core/libs.min.js' %}"></script>
  <!-- Plugin Scripts -->
  
  
  
  
  
  
  <!-- Lodash Utility -->
  <script src="{% static 'assets/vendor/lodash/lodash.min.js' %}"></script>
  <!-- External Library Bundle Script -->
  <script src="{% static 'assets/js/core/external.min.js' %}"></script>
  <!-- countdown Script -->
  <script src="{% static 'assets/js/plugins/countdown.js' %}"></script>
  <!-- utility Script -->
  <script src="{% static 'assets/js/utility.js' %}"></script>
  <!-- Setting Script -->
  <script src="{% static 'assets/js/setting.js' %}"></script>
  <script src="{% static 'assets/js/setting-init.js' %}" defer></script>
  <!-- Streamit Script -->
  <script src="{% static 'assets/js/streamit.js' %}" defer></script>
  <script src="{% static 'assets/js/swiper.js' %}" defer></script>
</body>

</html>

templates/user/register.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="dark">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>StreamIT | Responsive Bootstrap 5 Template</title>
  <!-- Google Font Api KEY-->
  <meta name="google_font_api" content="AIzaSyBG58yNdAjc20_8jAvLNSVi9E4Xhwjau_k">
  
  <!-- Favicon -->
  <link rel="shortcut icon" href="assets/images/favicon.ico" />
  
  <!-- Library / Plugin Css Build -->
  <link rel="stylesheet" href="{% static 'assets/css/core/libs.min.css' %}" />
  
  <!-- font-awesome css -->
  <link rel="stylesheet" href="{% static 'assets/vendor/font-awesome/css/all.min.css' %}" />
  
  <!-- Iconly css -->
  <link rel="stylesheet" href="{% static 'assets/vendor/iconly/css/style.css' %}" />
  
  <!-- Animate css -->
  <link rel="stylesheet" href="{% static 'assets/vendor/animate.min.css' %}" />
  
  
  
  
  
  
  <!-- Streamit Design System Css -->
  <link rel="stylesheet" href="{% static "assets/css/streamit.min848f.css" %}" />
  
  <!-- Custom Css -->
  <link rel="stylesheet" href="{% static "assets/css/custom.min848f.css" %}" />
  
  <!-- Rtl Css -->
  <link rel="stylesheet" href="{% static "assets/css/rtl.min848f.css" %}" />
  
  <!-- Google Font -->
  <link rel="preconnect" href="https://fonts.googleapis.com/">
  <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,300;0,400;0,500;0,700;0,900;1,300&amp;display=swap" rel="stylesheet">
  
</head>

<body class="  ">
  <span class="screen-darken"></span>
  <!-- loader Start -->
   <!-- loader Start -->
  <div class="loader simple-loader">
     <div class="loader-body">
        <img src="{% static 'assets/images/loader.gif' %}" alt="loader" class="img-fluid " width="300">
      </div>
  </div>
  <!-- loader END -->  <!-- loader END -->
  <main class="main-content">
      <!--Nav Start--> 
      <!--Nav End-->

      <!--bread-crumb-->
      <!--bread-crumb-->


<div class="vh-100" style="background: url('{% static "assets/images/pages/01.html" %}'); background-size: cover; background-repeat: no-repeat; position: relative;min-height:500px">
  <div class="container">
    <div class="row justify-content-center align-items-center height-self-center vh-100">
        <div class="col-lg-5 col-md-12 align-self-center">
            <div class="user-login-card bg-body">
               <h4 class="text-center mb-5">Create Your Account</h4>
               
                <form method="POST">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label class="text-white fw-500 mb-2">Email Address</label>
                        <input type="email" class="form-control rounded-1" name="email" placeholder="Johndoe@gmail.com" required="">
                    </div>
                    <div class="mb-3">
                        <label class="text-white fw-500 mb-2">Full Name</label>
                        <input type="text" class="form-control rounded-1" name="full_name" placeholder="John Doe" required="">
                    </div>
                    <div class="mb-3">
                        <label class="text-white fw-500 mb-2">Phone Number</label>
                        <input type="tel" class="form-control rounded-1" name="phone_number" placeholder="+21290567894" required="">
                    </div>
                    <div class="mb-3">
                        <label class="text-white fw-500 mb-2">Password</label>
                        <input type="password" class="form-control rounded-1" name="password" placeholder="*********" required="">
                    </div>

                    <div class="row text-center">
                        <div class="col-lg-3"></div>
                        <div class="col-lg-6">
                        <div class="full-button">
                            <div class="iq-button">
                                <button class="btn btn-black d-block" id="registerBtn" type="submit">Create my account</button>
                            </div>
                            <p class="mt-2 mb-0 fw-normal">Have an account?<a href="{% url "userauths:sign-in" %}" class="ms-1">Login</a></p>
                        </div>
                        </div>
                        <div class="col-lg-3"></div>
                    </div>
                </form>
              
              
              
            </div>
        </div>
    </div>
  </div>
</div>

  </main>



 <div id="back-to-top" style="display: none;">
     <a class="p-0 btn bg-primary btn-sm position-fixed top border-0 rounded-circle text-white" id="top" href="#top">
        <i class="fa-solid fa-chevron-up"></i>
     </a>
  </div>
  <!-- Wrapper End-->
  <!-- Library Bundle Script -->
  <script src="{% static 'assets/js/core/libs.min.js' %}"></script>
  <!-- Plugin Scripts -->
  
  
  
  
  
  
  <!-- Lodash Utility -->
  <script src="{% static 'assets/vendor/lodash/lodash.min.js' %}"></script>
  <!-- External Library Bundle Script -->
  <script src="{% static 'assets/js/core/external.min.js' %}"></script>
  <!-- countdown Script -->
  <script src="{% static 'assets/js/plugins/countdown.js' %}"></script>
  <!-- utility Script -->
  <script src="{% static 'assets/js/utility.js' %}"></script>
  <!-- Setting Script -->
  <script src="{% static 'assets/js/setting.js' %}"></script>
  <script src="{% static 'assets/js/setting-init.js' %}" defer></script>
  <!-- Streamit Script -->
  <script src="{% static 'assets/js/streamit.js' %}" defer></script>
  <script src="{% static 'assets/js/swiper.js' %}" defer></script>
</body>

</html>